Repository ISTESRMNCR/CODE-CAMP-2020, pull requests merged in 2020-07, with the labels that each got.

#4 Fix typo and image fit for sponsors section
  src/components/sponsor.js
  src/styles/styles.css
Labels: #contributor, </> 🙏 Appreciation, Good-to-merge, enhancement

#12 Registering TEAM Code Hard
  content/teams/Code Hard/index.md
Labels: Good-to-merge

#11 THANSR
  content/teams/THANSR/index.md
Labels: Good-to-merge

#13 Registering Team Agile
  content/teams/Agile/index.md
  content/teams/Code Hard/index.md
  content/teams/THANSR/index.md
Labels: Good-to-merge

#16 Craftify
  content/teams/Code Blooded/Index.md
Labels: Changes Requested, Have a Re-check, bug

#17 Registering TEAM [ MangNOVA ]
  content/teams/MangNOVA/index.md
Labels: Good-to-merge

#22 Registering Pull Request for Team Web-Alpha Clan
  content/teams/Web-Alpha Clan/index.md
Labels: Good-to-merge

#20 Registering TEAM codeAR
  content/teams/codeAR/index.md
Labels: Good-to-merge

#23 Registering TEAM [The Coding Hush]
  content/teams/The Coding Hush/index.md
Labels: Good-to-merge

#27 Registering TEAM [MATRIX]
  content/teams/MATRIX/index.md
Labels: Good-to-merge

#28 Registering team DKode
  content/teams/DKode/index.md
Labels: Good-to-merge

#29 grow together app
  Abstract.pdf
  In this app.docx
  content/teams/GrowTogether/index.md
Labels: Good-to-merge

#33 Registering TEAM [ Constant Variables ]
  content/teams/Constant Variables/index.md
Labels: Good-to-merge

#39 Registering Team Tstar
  content/teams/Tstar/index.md
Labels: Pending

#36 TechBrave
  content/teams/TechBrave/index.md
Labels: Good-to-merge

#38 Registering TEAM M.A.R.S.S.Z
  content/teams/M.A.R.S.S.Z/index.md
Labels: Good-to-merge

#35 Registering TEAM FS
  content/teams/FS/index.md
Labels: Good-to-merge

#41 Registering TEAM Utopians
  content/teams/Utopians/index.md
Labels: Good-to-merge

#45 Registering TEAM Z3Nspyder
  content/teams/Z3Nspyder/index.md
Labels: Good-to-merge

#49 Team Tycoons Registration
  content/teams/Tycoons/index.md
Labels: Good-to-merge

#51 Registering 12am_coder
  content/teams/12am_coder/index.md
Labels: Good-to-merge

#52 Divyanshutw code camp
  content/teams/Unskilled Developers/index.md
Labels: Good-to-merge

#53 Registering Team[Electronics_Creed]
  content/teams/Electronics_Creed/index.md
Labels: Good-to-merge

#55 Registering TEAM CodingDiva
  content/teams/CodingDiva/index.md
Labels: Good-to-merge

#56 Registering TEAM Boolean
  content/teams/Boolean/index.md
Labels: Good-to-merge

#58 Create index.md
  content/teams/decodeIt/index.md
Labels: Good-to-merge, Pending

#61 Registering TEAM Code_Undefined
  content/teams/Code_Undefined/index.md
Labels: Good-to-merge

#62 Registering TEAM FREAKS
  content/teams/Freaks/index.md
Labels: Good-to-merge

#57 Registering team[JustCodeIt]
  content/teams/JustCodeIt/index.md
Labels: Good-to-merge

#59 Registering Team BlockCoder
  content/teams/BlockCoder/index.md
Labels: Good-to-merge

#64 Create index.md
  content/teams/bug-byte/index.md
Labels: Good-to-merge

#74 Entry for finals [Tstar]
  content/finalist/Tstar/index.md
Labels: Good-to-merge

#75 Entry For Finals [MangNOVA]
  content/finalist/MangNOVA/index.md
Labels: Good-to-merge

#76 Entry For Finals [TheJuniorDev]
  content/finalist/TheJuniorDev/index.md
Labels: Good-to-merge

#80 Entry for finals (THANSR)
  content/finalist/THANSR/index.md
Labels: Good-to-merge

#81 Final Submission by TEAM ALPHA Q
  content/finalist/ALPHA Q/index.md
Labels: Changes Requested, Pending

#83 Entry for finals Team Agile
  content/finalist/Agile/index.md
Labels: Good-to-merge

#87 Entry for Finals [Electronics_Creed]
  content/finalist/Electronics_Creed/index.md
Labels: Good-to-merge

#88 Entry for finals team CodingDiva
  content/finalist/CodingDiva/index.md
Labels: Changes Requested, Pending

#89 Entry for finals [Unskilled Developers]
  content/finalist/Unskilled Developers/index.md
Labels: Good-to-merge

#91 Entry for Finals[ Web-Alpha Clan ]
  content/finalist/Web-Alpha Clan/index.md
Labels: Good-to-merge

#94 Entry for Finals [ Freaks ]
  content/finalist/Freaks/index.md
Labels: Good-to-merge

#90 Voomp submission
  content/finalist/Voomp/index.md
Labels: Good-to-merge

#97 Tycoons Entry for Final PR
  content/finalist/Tycoons/index.md
  content/teams/Tycoons/index.md
Labels: Changes Requested, Pending

#96 Entry for Final
  content/finalist/Codeplay/index.md
Labels: Good-to-merge

#102 Entry for Finals Z3Nspyder
  content/finalist/Z3Nspyder/index.md
Labels: Pending

#99 pr submission
  content/finalist/bug-byte/index.md
Labels: Good-to-merge

#106 Final Submission
  content/finalist/TheGlitch/index.md
Labels: Good-to-merge

#107 Entry for Team FS
  content/finalist/Team FS/index.md
Labels: Good-to-merge

#112 finalist corrections made
  content/finalist/Constant Variable/index.md
Labels: Changes Requested, Good-to-merge

#113 Entry For Finals Code Blooded
  content/finalist/Code Blooded/index.md
Labels: Good-to-merge

#117 Entry for finals [The Coding Hush]
  content/finalist/The Coding Hush/index.md
Labels: Closed, Instructions Not Followed, invalid
